# Generated by Django 4.2.3 on 2023-08-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('features', models.CharField(max_length=200)),
            ],
        ),
    ]
